setwd("C:/dsge/r3/")

################################################################
# Read Simulated Macroeconomic Factors by the DSGE Model #######
################################################################
macrofac <- read.csv("input/usp_simul.csv",header = FALSE) #This is generated by the dynare DSGE model
# Select the factors used for multifactor regression
vars <- c("y",
"c",
"i",
"g",
"imp",
"ex",
"q",
"c_m",
"i_m",
"i_d",
"pi_cbar",
"pi_c",
"pi_i",
"pi_d",
"pi_mc",
"pi_mi",
"pi_x",
"mc_d",
"mc_mc",
"mc_mi",
"mc_x",
"r_k",
"w",
"P_k",
"mu_z",
"kbar",
"k",
"u",
"dS",
"x",
"R",
"a",
"psi_z",
"H",
"E",
"gamma_mcd",
"gamma_mid",
"gamma_xstar",
"gamma_cd",
"gamma_id",
"gamma_f",
"R_star",
"pi_star",
"y_star",
"e_ystar",
"e_pistar",
"R4",
"pi_d4",
"pi_c4",
"pi_mc4",
"pi_mi4",
"e_c",
"e_i",
"e_a",
"e_z",
"e_H",
"lambda_x",
"lambda_d",
"lambda_mc",
"lambda_mi",
"z_tildestar",
"i_k",
"i_c",
"i_y",
"i_w",
"R_",
"pi_c_",
"pi_cbar_",
"pi_i_",
"pi_d_",
"dy_",
"dc_",
"di_",
"dimp_",
"dex_",
"dy_star_",
"pi_star_",
"R_star_",
"dE_",
"dS_",
"dw_",
"AUX_ENDO_LAG_25_1")

cols <- c("R_","pi_c_","pi_i_","pi_d_","dy_","dc_","di_","dimp_","dex_","dE_","dS_","dw_","dy_star_","pi_star_","R_star_")

#get needed columns of one simulation
getSim <- function(sim_result, sim, cols){
	data <- sim_result[,sim]
	nperiod <- length(data)/82
	ncols <- length(cols)
	results <- matrix(0, nperiod, ncols)
	col_idx <- match(cols, vars)
	i <- 1
	for (idx in col_idx) {
		rows <- seq(idx, idx+82*(nperiod-1), by = 82)
		results[,i] = data[rows]
		i = i+1
	}
	
	results <- as.data.frame(results)
	colnames(results) <- cols
	return(results)
}
#getSim(macrofac,2,cols)

#get needed columns of one period
getPeriod <- function(sim_result, period, cols){
	data <- sim_result[(82*(period-1)+1):(82*period),]
	nsim <- ncol(data)
	ncols <- length(cols)
	results <- matrix(0, nsim, ncols)
	col_idx <- match(cols, vars)
	i <- 1
	for (idx in col_idx) {
		results[,i] = as.numeric(data[idx,])
		i = i+1
	}
	
	results <- as.data.frame(results)
	colnames(results) <- cols
	return(results)
}
#getPeriod(macrofac,2,cols)

getAll <- function(sim_result, cols){
	nperiod <- nrow(sim_result)/82
	nsim <- ncol(sim_result)
	results <- getPeriod(sim_result,1,cols)
	if (nperiod > 1){
		for (i in c(2:nperiod)){
			temp <- getPeriod(sim_result,i,cols)
			results <- rbind(results, temp)
		}
	}
	return(results)
}
all <- getAll(macrofac,cols)

# multifactor model
mapping <- read.csv("input/mapping.csv")
mappingNames <- colnames(mapping)[2:(ncol(mapping)-6)]
normalchol <- read.csv("input/normalchol.csv")
recessionchol <- read.csv("input/recessionchol.csv")
inputmap <- read.csv("input/inputmap.csv", header=TRUE, sep=",", dec=".")
Xnames <- c("R_","pi_c_","pi_i_","pi_d_","dy_","dc_","di_","dimp_","dex_","dE_","dS_","dw_","dy_star_","pi_star_","R_star_")
Ynames <- names(inputmap)[!names(inputmap) %in% c(Xnames,"Year","Quarter","Recession")]
histAR <- inputmap[,names(inputmap) %in% Ynames]
histAR <- histAR[(nrow(histAR)-1):nrow(histAR),]
histMF <- inputmap[,names(inputmap) %in% Xnames]
histMF <- histMF[(nrow(histMF)-1):nrow(histMF),]
histRecession <- inputmap[(nrow(inputmap)-1):nrow(inputmap),names(inputmap) %in% c("Recession")]

#Recession Logistic function
recession <- function(paras, vals){
	prob <- 1/(1+exp(-sum(paras * vals)))
	if(prob > 0.5) {
		return(1)
	}else{
		return(0)
	}
}

recession_paras <- c(-78.9314371472467,58.4192888697771,-85.6712386712998,1.25737716846569,
						-3.81105083852229,-158.043520798996,4.14972659354834,-0.926564319110315,
						8.78661754401086,-5.03557685494598,-68.2566628501183,50.839037238919,
						1.58440952276003,-74.9761852953987,17.2116954501545,86.5282087758338)

# Intercept, pi_c_, dy_, dc_, di_, dE_, pi_c_1, dy_1, dc_1, di_1, dE_1, pi_c_2, dy_2, dc_2, di_2, dE_2

set.seed(6)
# ESG: create one single scenario
esg <- function(fundmap,histMF,histAR,cholNormal,cholRecession,macrofac,period, sim){
	sim_mf <- rbind(histMF, macrofac[(200*(sim-1)+1):(200*(sim-1)+period),])
	mappingX <- sim_mf
	sim_mf$recession <- 0
	sim_mf$recession[1:2] <- histRecession
	recessionX = sim_mf[, names(sim_mf) %in% c("pi_c_", "dy_", "dc_", "di_", "dE_")]
	lag <-2
	recessionNames <- c("pi_c_", "dy_", "dc_", "di_", "dE_")
	if (lag > 0) {
		for (i in c(1:lag)){
			for (varname in recessionNames){
				recessionX[(i+1):nrow(recessionX),paste0(varname,i)] <- recessionX[1:(nrow(recessionX)-i),varname]
				recessionX[1:i,paste0(varname,i)] <- NA
			}
		}
	}
	recessionX <- recessionX[(lag+1):nrow(recessionX),]
	recessionX <- cbind(Intercept = 1, recessionX)
	for (i in c(3:nrow(sim_mf))) {
		sim_mf$recession[i] <- recession(recession_paras,recessionX[i-2,])
	}
	
	sim_mf <- cbind(sim_mf,histAR)
	
	sdtnormal <- sqrt(fundmap[,names(fundmap) %in% c("tvar")])
	sdtrecession <- sqrt(fundmap[,names(fundmap) %in% c("trvar")])
	sdinormal <- sqrt(fundmap[,names(fundmap) %in% c("ivar")])
	sdirecession <- sqrt(fundmap[,names(fundmap) %in% c("irvar")])
	corrnormal <- fundmap[,names(fundmap) %in% c("tcorr")]
	corrrecession <- fundmap[,names(fundmap) %in% c("rcorr")]

	lag <-2
	if (lag > 0) {
		for (i in c(1:lag)){
			for (varname in Xnames){
				mappingX[(i+1):nrow(mappingX),paste0(varname,i)] <- mappingX[1:(nrow(mappingX)-i),varname]
				mappingX[1:i,paste0(varname,i)] <- NA
			}
		}
	}
	mappingX <- mappingX[, colnames(fundmap)[5:(ncol(fundmap)-6)]]

	for (i in c(1:period)){
		mappingX_i <- mappingX[i+2,]
		mappingX_i <- data.frame(c(1,0,0,mappingX_i))
		colnames(mappingX_i) <- mappingNames

		mappingX_i_m <- as.data.frame(lapply(mappingX_i, rep, length(sdinormal)))
		mappingX_i_m$x2 <- as.numeric(sim_mf[i,c(17:ncol(sim_mf))])
		mappingX_i_m$x1 <- as.numeric(sim_mf[i+1,c(17:ncol(sim_mf))])
		
		mappingfunc <- fundmap[,2:(ncol(fundmap)-6)]
		det_returns = rowSums(mappingfunc * mappingX_i_m)

		if (sim_mf$recession[i+2]==0){
			rnds <- t(data.matrix(normalchol)) %*% (sdinormal * rnorm(length(sdinormal)))
			rnds <- as.numeric(rnds)
			rnds[14] <- 0
		}else{
			rnds <- t(data.matrix(recessionchol)) %*% (sdirecession * rnorm(length(sdirecession)))
			rnds <- (corrrecession * det_returns + sqrt(1-corrrecession*corrrecession)*rnds) * sdirecession
			rnds <- as.numeric(rnds)/sqrt(corrrecession * corrrecession * sdtrecession * sdtrecession+(1-corrrecession*corrrecession)*sdirecession*sdirecession)
			rnds[14] <- 0
		}
		sim_mf[i+2,c(17:ncol(sim_mf))] <- det_returns + as.numeric(rnds)*1
	}
	return(sim_mf)
}
#one_scn <- esg(mapping,histMF,histAR,normalchol,recessionchol,all,80,20)

set.seed(6)
nsims <- 9999
zero_scn <- esg(mapping,histMF,histAR,normalchol,recessionchol,all_revised,80,1)

for (i in c(1:nsims)){
	isim <- i %% 1000
	if (isim==0) {isim=1000}
	one_scn <- esg(mapping,histMF,histAR,normalchol,recessionchol,all_revised,80,isim)
	zero_scn <- rbind(zero_scn, one_scn)
	if (i %% 10 == 0){print(paste0(i," simulations are done."))}
}

zero_scn$quarter <- rep(c((-1):80),10000)
write.csv(zero_scn,"esg_dsge.csv",row.names=FALSE)
